[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-utils = "0.1.4"
log = "0.4.17"
shared_models = { path = "../shared_models" }
wasm-bindgen = "0.2.81"
wasm-bindgen-futures = "0.4.31"
wasm-logger = "0.2.0"
yew = "0.19.3"
yew-router = "0.16.0"
serde_json = "1.0.82"

[dependencies.web-sys]
version = "0.3.58"
features = [
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
]
