[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
gloo-utils = "0.1.4"
log = "0.4.17"
serde = { version = "1.0.139", features = ["serde_derive"] }
serde_json = "1.0.82"
wasm-bindgen = "0.2.81"
wasm-bindgen-futures = "0.4.31"
wasm-logger = "0.2.0"
yew = "0.19.3"
yew-router = "0.16.0"
gloo-storage = "0.2.1"

[dependencies.web-sys]
version = "0.3.58"
features = [
    "Headers",
    "HtmlInputElement",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
]
