[package]
name = "frontend"
version = "0.3.3"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
gloo-storage = "0.2.2"
gloo-utils = "0.1.5"
log = "0.4.17"
serde = { version = "1.0.147", features = ["serde_derive"] }
serde_json = "1.0.87"
shared = { path = "../shared" }
stylist = { version = "0.10.1", features = ["yew_integration"] }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
wasm-logger = "0.2.0"
yew = "0.19.3"
yew-hooks = "0.1.56"
yew-router = "0.16.0"
serde_urlencoded = "0.7.1"

[dependencies.web-sys]
version = "0.3.60"
features = [
    "Document",
    "Headers",
    "HtmlInputElement",
    "Location",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "ScrollBehavior",
    "ScrollToOptions",
    "Window",
]
