[package]
name = "frontend"
version = "0.2.2"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
gloo-utils = "0.1.5"
log = "0.4.17"
serde = { version = "1.0.145", features = ["serde_derive"] }
serde_json = "1.0.86"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
wasm-logger = "0.2.0"
yew = "0.19.3"
yew-router = "0.16.0"
gloo-storage = "0.2.2"
yew-hooks = "0.1.56"

[dependencies.web-sys]
version = "0.3.60"
features = [
    "Document",
    "Headers",
    "HtmlInputElement",
    "Location",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
]
