[package]
name = "backend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.0.1"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.17"
r2d2 = "0.8.9"
serde_json = "1.0.81"

[dependencies.chrono]
version = "0.4.19"
features = [
  "serde",
]

[dependencies.diesel]
version = "1.4.8"
features = [
  "chrono",
  "postgres",
  "r2d2",
]

[dependencies.serde]
version = "1.0.137"
features = [
  "serde_derive",
]

[dependencies.uuid]
version = "1.1.0"
features = [
  "serde",
  "v4",
]
