[package]
name = "backend"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.1.0"
calibre = { path = "../calibre" }
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.2.8"
diesel = { version = "1.4.8", features = ["chrono", "postgres", "r2d2"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.21"
log = "0.4.17"
mongodb = "2.2.2"
r2d2 = "0.8.10"
serde = { version = "1.0.139", features = ["serde_derive"] }
serde_json = "1.0.82"
shell-rs = "0.2.5"
tokio = { version = "1.19.2", features = [ "full", ] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
