[package]
name = "backend"
version = "0.3.3"
edition = "2021"
publish = false

[dependencies]
actix-files = "0.6.2"
actix-http = "3.2.2"
actix-rt = "2.7.0"
actix-web = "4.2.1"
actix-web-grants = "3.0.1"
actix-web-httpauth = "0.8.0"
calibre = { path = "../calibre" }
chrono = { version = "0.4.22", default-features = false, features = ["serde", "std"] }
clap = "4.0.20"
data-encoding = "2.3.2"
diesel = { version = "2.0.2", default-features = false, features = ["chrono", "postgres", "r2d2"] }
dotenv = "0.15.0"
env_logger = "0.9.2"
futures = "0.3.25"
hmac = "0.12.1"
image = { version = "0.24.4", default-features = false, features = ["jpeg", "png", "scoped_threadpool", "webp", "webp-encoder"] }
jsonwebtoken = "8.1.1"
log = "0.4.17"
r2d2 = "0.8.10"
ring = { version = "0.16.20", features = ["std"] }
serde = { version = "1.0.147", features = ["serde_derive"] }
serde_json = "1.0.87"
shared = { path = "../shared", features = ["use_query"] }
tokio = { version = "1.21.2", features = [ "full", ] }
urlencoding = "2.1.2"
uuid = { version = "1.2.1", features = ["serde", "v4"] }

[build-dependencies]
vergen = "7.4.2"
