[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
diesel = { version = "1.4.8", features = [ "postgres", "r2d2", ] }
dotenv = "0.15.0"
serde = { version = "1.0.137", features = [ "serde_derive" ] }
serde_json = "1.0.81"
