version: "2.0"
services:
    db:
        image: mongo:4.4
        restart: always
        ports:
            - 127.0.0.1:27017:27017
            - 127.0.0.1:27018:27018
        volumes:
            - ./db:/data/db
