version: "3.0"
services:
  redis:
    image: postgres:14.3
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: library-password
      POSTGRES_USER: postgres
      POSTGRES_DB: library
    volumes:
      - ./db:/var/lib/postgresql
      - ./db/data:/var/lib/postgresql/data
