version: "3.0"
services:
  library_db:
    image: postgres:14.3
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: library-password
      POSTGRES_USER: postgres
      POSTGRES_DB: library
    volumes:
      - /docker/library:/var/lib/postgresql
      - /docker/library/data:/var/lib/postgresql/data
